{
 "title": "DNS-CHECK",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host for ip tables",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "IP status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS GOOGLE CHECK PROD",
   "type": "table",
   "description": "8.8.8.8",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "url_prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ipres1" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS YANDEX-1 CHECK PROD",
   "type": "table",
   "description": "77.88.8.8",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "url_prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ipres2" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS YANDEX-2 CHECK PROD",
   "type": "table",
   "description": "77.88.8.1",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "url_prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ipres3" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS GOOGLE CHECK DEMO",
   "type": "table",
   "description": "8.8.8.8",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "url_demo" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ipres1" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS YANDEX-1 CHECK DEMO",
   "type": "table",
   "description": "77.88.8.8",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "url_demo" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ipres2" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS YANDEX-2 CHECK DEMO",
   "type": "table",
   "description": "77.88.8.1",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "url_demo" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ipres3" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status resolv",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS GOOGLE CHECK PROD",
     "type": "stat",
     "description": "8.8.8.8",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_prod" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status1" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "DNS YANDEX-1 CHECK PROD",
     "type": "stat",
     "description": "77.88.8.8",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_prod" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status2" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "DNS YANDEX-2 CHECK PROD",
     "type": "stat",
     "description": "77.88.8.1",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_prod" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status3" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "DNS GOOGLE CHECK DEMO",
     "type": "stat",
     "description": "8.8.8.8",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_demo" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status1" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "DNS YANDEX-1 CHECK DEMO",
     "type": "stat",
     "description": "77.88.8.8",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_demo" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status2" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "DNS YANDEX-2 CHECK DEMO",
     "type": "stat",
     "description": "77.88.8.1",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_demo" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status3" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "GOOGLE DNS CHECK PROD",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_prod" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status1" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "YANDEX-1 DNS CHECK PROD",
     "type": "timeseries",
     "description": "77.88.8.8",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_prod" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status2" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "YANDEX-2 DNS CHECK PROD",
     "type": "timeseries",
     "description": "77.88.8.1",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_prod" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status3" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "GOOGLE DNS CHECK DEMO",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_demo" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status1" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "YANDEX-1 DNS CHECK DEMO",
     "type": "timeseries",
     "description": "77.88.8.8",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_demo" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status2" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "YANDEX-2 DNS CHECK DEMO",
     "type": "timeseries",
     "description": "77.88.8.1",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "url_demo" },
       "host": { "filter": "/.*/" },
       "item": { "filter": "Status3" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "IP TABLS RESOLVED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GOOGLE DNS IP RESOLVED $host",
     "type": "table",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "/url.*/" },
       "host": { "filter": "$host" },
       "item": { "filter": "ipres1" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "YANDEX-1 DNS IP RESOLVED $host",
     "type": "table",
     "gridPos": { "h": 15, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "/url.*/" },
       "host": { "filter": "$host" },
       "item": { "filter": "ipres2" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "YANDEX-2 DNS IP RESOLVED $host",
     "type": "table",
     "gridPos": { "h": 15, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "/url.*/" },
       "host": { "filter": "$host" },
       "item": { "filter": "ipres3" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}